## 00.PyTorch Fundamentals

Resourcs notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

if any  question : https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.3.1+cu121


In [ ]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

tensor(7)

In [ ]:
scalar.ndim

0

0

In [ ]:
#getting tensor int value
scalar.item()

7

7

In [ ]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

tensor([7, 7])

In [ ]:
vector.ndim

1

1

In [ ]:
vector.shape

torch.Size([2])

torch.Size([2])

In [ ]:
#Matrix
matrix = torch.tensor([[7 , 8],[9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
matrix.ndim
matrix.shape

torch.Size([2, 2])

torch.Size([2, 2])

In [ ]:
matrix.ndim

2

2

In [ ]:
matrix[1]

tensor([ 9, 10])

tensor([ 9, 10])

In [ ]:
#Tensor
Tensor = torch.tensor([[[1,2,3],[3,4,5],[1,2,3],[1,2,4]],[[1,2,3],[3,4,5],[1,2,3],[1,2,4]]])
Tensor

tensor([[[1, 2, 3],
         [3, 4, 5],
         [1, 2, 3],
         [1, 2, 4]],

        [[1, 2, 3],
         [3, 4, 5],
         [1, 2, 3],
         [1, 2, 4]]])

tensor([[[1, 2, 3],
         [3, 4, 5],
         [1, 2, 3],
         [1, 2, 4]],

        [[1, 2, 3],
         [3, 4, 5],
         [1, 2, 3],
         [1, 2, 4]]])

In [ ]:
Tensor.shape

torch.Size([2, 4, 3])

torch.Size([2, 4, 3])

In [ ]:
Tensor.ndim

3

3

Random Tensors

In [ ]:
#create a random tensor
random_tensor = torch.rand(2, 3 , 4)
random_tensor

tensor([[[0.4946, 0.9831, 0.5134, 0.2580],
         [0.5002, 0.6152, 0.6283, 0.6972],
         [0.5420, 0.5651, 0.0891, 0.8486]],

        [[0.1901, 0.3035, 0.6512, 0.4057],
         [0.8156, 0.6753, 0.9405, 0.6498],
         [0.6329, 0.6110, 0.1847, 0.5707]]])

tensor([[[0.4946, 0.9831, 0.5134, 0.2580],
         [0.5002, 0.6152, 0.6283, 0.6972],
         [0.5420, 0.5651, 0.0891, 0.8486]],

        [[0.1901, 0.3035, 0.6512, 0.4057],
         [0.8156, 0.6753, 0.9405, 0.6498],
         [0.6329, 0.6110, 0.1847, 0.5707]]])

In [ ]:
random_tensor.shape

torch.Size([2, 3, 4])

torch.Size([2, 3, 4])

In [ ]:
random_tensor.ndim

3

3

In [ ]:
#random image tensor
random_image = torch.rand(size=(3,224,224)) #color channel height and width
random_image

tensor([[[0.6729, 0.3982, 0.2390,  ..., 0.0706, 0.4915, 0.0271],
         [0.1605, 0.2498, 0.2933,  ..., 0.2598, 0.8573, 0.0043],
         [0.1394, 0.4947, 0.5618,  ..., 0.4996, 0.0972, 0.5370],
         ...,
         [0.0534, 0.7938, 0.7199,  ..., 0.9415, 0.7492, 0.2395],
         [0.9476, 0.6589, 0.7405,  ..., 0.4703, 0.3070, 0.9822],
         [0.6930, 0.3673, 0.0524,  ..., 0.1304, 0.2537, 0.4038]],

        [[0.7338, 0.9835, 0.2133,  ..., 0.5384, 0.8942, 0.6525],
         [0.0844, 0.4533, 0.9153,  ..., 0.7265, 0.8840, 0.7803],
         [0.0502, 0.3853, 0.2367,  ..., 0.4656, 0.1035, 0.7067],
         ...,
         [0.8435, 0.0407, 0.3668,  ..., 0.4787, 0.3913, 0.7235],
         [0.5404, 0.9414, 0.1325,  ..., 0.7289, 0.6707, 0.7171],
         [0.2546, 0.2445, 0.0889,  ..., 0.4869, 0.6404, 0.7220]],

        [[0.9101, 0.7012, 0.0682,  ..., 0.1552, 0.3965, 0.7666],
         [0.6416, 0.6428, 0.1920,  ..., 0.1617, 0.0357, 0.9295],
         [0.7122, 0.6062, 0.8346,  ..., 0.1378, 0.6569, 0.

tensor([[[0.6729, 0.3982, 0.2390,  ..., 0.0706, 0.4915, 0.0271],
         [0.1605, 0.2498, 0.2933,  ..., 0.2598, 0.8573, 0.0043],
         [0.1394, 0.4947, 0.5618,  ..., 0.4996, 0.0972, 0.5370],
         ...,
         [0.0534, 0.7938, 0.7199,  ..., 0.9415, 0.7492, 0.2395],
         [0.9476, 0.6589, 0.7405,  ..., 0.4703, 0.3070, 0.9822],
         [0.6930, 0.3673, 0.0524,  ..., 0.1304, 0.2537, 0.4038]],

        [[0.7338, 0.9835, 0.2133,  ..., 0.5384, 0.8942, 0.6525],
         [0.0844, 0.4533, 0.9153,  ..., 0.7265, 0.8840, 0.7803],
         [0.0502, 0.3853, 0.2367,  ..., 0.4656, 0.1035, 0.7067],
         ...,
         [0.8435, 0.0407, 0.3668,  ..., 0.4787, 0.3913, 0.7235],
         [0.5404, 0.9414, 0.1325,  ..., 0.7289, 0.6707, 0.7171],
         [0.2546, 0.2445, 0.0889,  ..., 0.4869, 0.6404, 0.7220]],

        [[0.9101, 0.7012, 0.0682,  ..., 0.1552, 0.3965, 0.7666],
         [0.6416, 0.6428, 0.1920,  ..., 0.1617, 0.0357, 0.9295],
         [0.7122, 0.6062, 0.8346,  ..., 0.1378, 0.6569, 0.

In [ ]:
random_image.shape , random_image.ndim

(torch.Size([3, 224, 224]), 3)

(torch.Size([3, 224, 224]), 3)

In [ ]:
#zero's tensor
zero = torch.zeros(3,4)
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zero * random_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
zero.dtype

torch.float32

torch.float32

In [ ]:
random_tensor.dtype

torch.float32

torch.float32

In [ ]:
matrix.dtype

torch.int64

torch.int64

In [ ]:
scalar.dtype

torch.int64

torch.int64

In [ ]:
vector.dtype

torch.int64

torch.int64

In [ ]:
#ones tensor
one = torch.ones(3,4)
one

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
#creating a range
one_to_ten_range = torch.arange(0,11,2) #start stop hops
one_to_ten_range

tensor([ 0,  2,  4,  6,  8, 10])

tensor([ 0,  2,  4,  6,  8, 10])

In [ ]:
one_to_ten_range.shape

torch.Size([6])

torch.Size([6])

In [ ]:
#Creating a list of ten to zeroes
ten_to_zeroes = torch.zeros_like(input= one_to_ten_range)
ten_to_zeroes

tensor([0, 0, 0, 0, 0, 0])

tensor([0, 0, 0, 0, 0, 0])

In [ ]:
#creating a list with ones
ten_to_one = torch.ones_like(input = one_to_ten_range)
ten_to_one

tensor([1, 1, 1, 1, 1, 1])

tensor([1, 1, 1, 1, 1, 1])

In [ ]:
#Float 32 tensor
float32_tensor = torch.tensor([[1,2] , [2,3] ,[3,4]])

In [ ]:
float32_tensor.dtype

torch.int64

torch.int64

In [ ]:
float16_tensor = float32_tensor.type(torch.float16)
float16_tensor

tensor([[1., 2.],
        [2., 3.],
        [3., 4.]], dtype=torch.float16)

tensor([[1., 2.],
        [2., 3.],
        [3., 4.]], dtype=torch.float16)

In [ ]:
float16_tensor * float32_tensor

tensor([[ 1.,  4.],
        [ 4.,  9.],
        [ 9., 16.]], dtype=torch.float16)

tensor([[ 1.,  4.],
        [ 4.,  9.],
        [ 9., 16.]], dtype=torch.float16)

In [ ]:
#test on tensor
some_tensor = torch.rand(3,5)
some_tensor

tensor([[0.4727, 0.9407, 0.6810, 0.2139, 0.3434],
        [0.7817, 0.0745, 0.7096, 0.5886, 0.6275],
        [0.4120, 0.4124, 0.5147, 0.8076, 0.8826]])

tensor([[0.4727, 0.9407, 0.6810, 0.2139, 0.3434],
        [0.7817, 0.0745, 0.7096, 0.5886, 0.6275],
        [0.4120, 0.4124, 0.5147, 0.8076, 0.8826]])

In [ ]:
some_tensor.dtype, some_tensor.shape, some_tensor.device

(torch.float32, torch.Size([3, 5]), device(type='cpu'))

(torch.float32, torch.Size([3, 5]), device(type='cpu'))

In [ ]:
some_tensor.type(torch.float32)
some_tensor.dtype

torch.float32

torch.float32

In [ ]:
new_some_tensor = some_tensor.type(torch.half)
new_some_tensor, new_some_tensor.device

(tensor([[0.4727, 0.9409, 0.6812, 0.2139, 0.3433],
         [0.7817, 0.0745, 0.7095, 0.5884, 0.6274],
         [0.4121, 0.4124, 0.5146, 0.8076, 0.8828]], dtype=torch.float16),
 device(type='cpu'))

(tensor([[0.4727, 0.9409, 0.6812, 0.2139, 0.3433],
         [0.7817, 0.0745, 0.7095, 0.5884, 0.6274],
         [0.4121, 0.4124, 0.5146, 0.8076, 0.8828]], dtype=torch.float16),
 device(type='cpu'))

In [ ]:
#tensor manipulation
tensors = torch.rand(1,2)
tensors

tensor([[0.8087, 0.0931]])

tensor([[0.8087, 0.0931]])

In [ ]:
tensors + 10

tensor([[10.8087, 10.0931]])

tensor([[10.8087, 10.0931]])

In [ ]:
tensors - 10

tensor([[-9.1913, -9.9069]])

tensor([[-9.1913, -9.9069]])

In [ ]:
tensors * 10

tensor([[8.0868, 0.9307]])

tensor([[8.0868, 0.9307]])

In [ ]:
tensors / 10

tensor([[0.0809, 0.0093]])

tensor([[0.0809, 0.0093]])

In [ ]:
tensors.add(10)

tensor([[10.8087, 10.0931]])

tensor([[10.8087, 10.0931]])

In [ ]:
print(tensors, "*" , tensors)
print(f"Equals:{tensors * tensors}")

tensor([[0.8087, 0.0931]]) * tensor([[0.8087, 0.0931]])
Equals:tensor([[0.6540, 0.0087]])
tensor([[0.8087, 0.0931]]) * tensor([[0.8087, 0.0931]])
Equals:tensor([[0.6540, 0.0087]])


In [ ]:
#Matrix multiplication
Matrixmul = torch.tensor([1,2,3])
Matrixmul

tensor([1, 2, 3])

tensor([1, 2, 3])

In [ ]:
torch.matmul(Matrixmul,Matrixmul)

tensor(14)

tensor(14)

In [ ]:
%%time
value = 0
for i in range(len(Matrixmul)):
  value += Matrixmul[i] * Matrixmul[i]
print(value)

tensor(14)
CPU times: user 1.88 ms, sys: 66 µs, total: 1.94 ms
Wall time: 4.27 ms
tensor(14)
CPU times: user 1.1 ms, sys: 0 ns, total: 1.1 ms
Wall time: 1.74 ms


In [ ]:
%%time
torch.matmul(Matrixmul,Matrixmul)

CPU times: user 42 µs, sys: 0 ns, total: 42 µs
Wall time: 46 µs


tensor(14)

CPU times: user 39 µs, sys: 3 µs, total: 42 µs
Wall time: 45.5 µs


tensor(14)

In [ ]:
Matrixmul.subtract(10)

tensor([-9, -8, -7])

tensor([-9, -8, -7])

In [ ]:
 #matrix multiplication for fixing shape issue
 Tensor_A = torch.tensor([[1,2,3] , [4,5,6]])
 Tensor_A

tensor([[1, 2, 3],
        [4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
Tensor_B = torch.tensor([[1,2,3] , [4,5,6]])
Tensor_B

tensor([[1, 2, 3],
        [4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
torch.mm(Tensor_A , Tensor_B.T).shape

torch.Size([2, 2])

torch.Size([2, 2])

In [ ]:
Tensor_B.shape , Tensor_B.T.shape , Tensor_A.shape

(torch.Size([2, 3]), torch.Size([3, 2]), torch.Size([2, 3]))

(torch.Size([2, 3]), torch.Size([3, 2]), torch.Size([2, 3]))

In [ ]:
#min max and average/mean
a = torch.arange(10 , 100,10)
a.shape

torch.Size([9])

torch.Size([9])

In [ ]:
a.min() , torch.min(a) , a.max() , torch.max(a),torch.mean(a.type(torch.half)) #for mean convert data type to float

(tensor(10),
 tensor(10),
 tensor(90),
 tensor(90),
 tensor(50., dtype=torch.float16))

(tensor(10),
 tensor(10),
 tensor(90),
 tensor(90),
 tensor(50., dtype=torch.float16))

In [ ]:
a.type(torch.half).mean() , torch.mean(a.type(torch.half))

(tensor(50., dtype=torch.float16), tensor(50., dtype=torch.float16))

(tensor(50., dtype=torch.float16), tensor(50., dtype=torch.float16))

In [ ]:
torch.sum(a) , a.sum()

(tensor(450), tensor(450))

(tensor(450), tensor(450))

In [ ]:
torch.argmin(a) , a.argmax() #following will help us to return the index of the list

(tensor(0), tensor(8))

(tensor(0), tensor(8))

In [ ]:
a.argsort()

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
a.sort()

torch.return_types.sort(
values=tensor([10, 20, 30, 40, 50, 60, 70, 80, 90]),
indices=tensor([0, 1, 2, 3, 4, 5, 6, 7, 8]))

torch.return_types.sort(
values=tensor([10, 20, 30, 40, 50, 60, 70, 80, 90]),
indices=tensor([0, 1, 2, 3, 4, 5, 6, 7, 8]))

In [ ]:
#reshape
a.shape

torch.Size([9])

torch.Size([9])

In [ ]:
newa = a.reshape(9,1)
newa , a

(tensor([[10],
         [20],
         [30],
         [40],
         [50],
         [60],
         [70],
         [80],
         [90]]),
 tensor([10, 20, 30, 40, 50, 60, 70, 80, 90]))

(tensor([[10],
         [20],
         [30],
         [40],
         [50],
         [60],
         [70],
         [80],
         [90]]),
 tensor([10, 20, 30, 40, 50, 60, 70, 80, 90]))

In [ ]:
b = torch.arange(110 , 200 , 10)
b , b.shape , b.dtype

(tensor([110, 120, 130, 140, 150, 160, 170, 180, 190]),
 torch.Size([9]),
 torch.int64)

(tensor([110, 120, 130, 140, 150, 160, 170, 180, 190]),
 torch.Size([9]),
 torch.int64)

In [ ]:
#stack a tensor on top of each other
x_stack = torch.stack([a,b,a,b], dim=0)   #to stack on each other the tensors should be of same shape.
x_stack

tensor([[ 10,  20,  30,  40,  50,  60,  70,  80,  90],
        [110, 120, 130, 140, 150, 160, 170, 180, 190],
        [ 10,  20,  30,  40,  50,  60,  70,  80,  90],
        [110, 120, 130, 140, 150, 160, 170, 180, 190]])

tensor([[ 10,  20,  30,  40,  50,  60,  70,  80,  90],
        [110, 120, 130, 140, 150, 160, 170, 180, 190],
        [ 10,  20,  30,  40,  50,  60,  70,  80,  90],
        [110, 120, 130, 140, 150, 160, 170, 180, 190]])

In [ ]:
#squeez and unsqueeze
x_squeeze = b.squeeze()
x_squeeze.shape

torch.Size([9])

torch.Size([9])

In [ ]:
unx_squeeze = b.unsqueeze(dim =1)
unx_squeeze.shape

torch.Size([9, 1])

torch.Size([9, 1])

In [ ]:
#rearrganging dimensions or shape in tensors using permute be aware it like view which means it shares same memory space
image_1 = torch.rand(size =(224 , 224 , 3))
image_1.shape

torch.Size([224, 224, 3])

torch.Size([224, 224, 3])

In [ ]:
permuted_image = image_1.permute(2,0,1)
permuted_image.shape

torch.Size([3, 224, 224])

torch.Size([3, 224, 224])

In [ ]:
#learn indexing
x = torch.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0][2][0]

tensor(7)

tensor(7)

In [ ]:
x[0,2,2]

tensor(9)

tensor(9)

In [ ]:
x[:,:,2]

tensor([[3, 6, 9]])

tensor([[3, 6, 9]])

In [ ]:
x[:,1,1]

tensor([5])

tensor([5])

In [ ]:
x[0,0,:]

tensor([1, 2, 3])

tensor([1, 2, 3])

In [ ]:
#challenge to return 9
x[:,2,2]

tensor([9])

tensor([9])

In [ ]:
x[0,2,2]

tensor(9)

tensor(9)

In [ ]:
x[:,:,2]

tensor([[3, 6, 9]])

tensor([[3, 6, 9]])

In [ ]:
#numpy array to tensor
array = np.arange(1,10,2)
array , array.dtype

(array([1, 3, 5, 7, 9]), dtype('int64'))

(array([1, 3, 5, 7, 9]), dtype('int64'))

In [ ]:
tarray = torch.from_numpy(array).type(torch.float32)
tarray , tarray.dtype

(tensor([1., 3., 5., 7., 9.]), torch.float32)

(tensor([1., 3., 5., 7., 9.]), torch.float32)

In [ ]:
array+1

array([ 2,  4,  6,  8, 10])

array([ 2,  4,  6,  8, 10])

In [ ]:
tarray.dtype

torch.float32

torch.float32

In [ ]:
narray = tarray.numpy()
narray.dtype, array.dtype , tarray.dtype

(dtype('float32'), dtype('int64'), torch.float32)

(dtype('float32'), dtype('int64'), torch.float32)

In [ ]:
#random seeds for reproducibility
Tensors_A = torch.rand(3,4)
Tensors_B = torch.rand(3,4)
print(Tensors_A == Tensors_B)

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
#Random seed declaration
random_seeds = 77
torch.manual_seed(random_seeds)  #used to reduce randomness in rand genertation
Tensor_C = torch.rand(3,4)
torch.manual_seed(random_seeds)
Tensor_D = torch.rand(3,4)
print(Tensor_C == Tensor_D)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [ ]:
torch.cuda.is_available() #check if GPU is available or not

True

In [ ]:
#for shortcut to check GPU or CPU
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
#To count number GPU available
torch.cuda.device_count()

1

In [ ]:
tensor_cpu = torch.tensor([1,2,3])
tensor_cpu , tensor_cpu.device

(tensor([1, 2, 3]), device(type='cpu'))

In [ ]:
#Change to GPU
tensor_gpu = tensor_cpu.to(device)
tensor_gpu

tensor([1, 2, 3], device='cuda:0')

In [ ]:
#to work with numpy we need to transfer the device back to cpu or else it wont work.
tensor_gpu.cpu().numpy()

array([1, 2, 3])

(tensor([[0.4946, 0.9831, 0.5134, 0.2580, 0.5002, 0.6152, 0.6283],
         [0.6972, 0.5420, 0.5651, 0.0891, 0.8486, 0.1901, 0.3035],
         [0.6512, 0.4057, 0.8156, 0.6753, 0.9405, 0.6498, 0.6329],
         [0.6110, 0.1847, 0.5707, 0.6729, 0.3982, 0.2390, 0.2084],
         [0.7921, 0.1592, 0.9983, 0.4600, 0.6405, 0.8427, 0.8737],
         [0.6508, 0.1006, 0.5123, 0.2961, 0.0813, 0.3255, 0.7400],
         [0.5685, 0.9510, 0.2281, 0.7452, 0.9047, 0.1822, 0.9578]]),
 torch.Size([7, 7]))